# Generated by Django 3.2.12 on 2023-05-15 16:03

from django.db import migrations, models
import django.db.models.deletion
import news.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=news.utils.ModelUtils.gen_save_img_location)),
                ('name', models.CharField(default='undefined', max_length=512)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('authors', models.ManyToManyField(to='news.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.department'),
        ),
    ]
