# Generated by Django 3.2.12 on 2023-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='authors',
        ),
        migrations.AddField(
            model_name='passage',
            name='author',
            field=models.CharField(default='undefined', max_length=32),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
