# Generated by Django 3.2.12 on 2023-05-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20230516_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='id',
        ),
        migrations.AddField(
            model_name='passage',
            name='passage_id',
            field=models.CharField(default='undefined', max_length=32, primary_key=True, serialize=False),
        ),
    ]
