# Generated by Django 3.2.12 on 2023-05-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20230517_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hash_md5',
            field=models.CharField(default='undefined', max_length=128),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passage_id',
            field=models.CharField(default='undefined', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passage',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
