# Generated by Django 3.2.12 on 2023-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20230519_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='number',
            field=models.IntegerField(auto_created=True, default=-1),
        ),
    ]
